#!/bin/bash

# A script that print your system username with a color

function myHelp () {
echo -e "

\e[0m*****
*****

\e[1;33mRun chmod U+x coloruser
\e[0m------
\e[1;31mthen execute the script 
\e[0m-----
\e[1;33m./coloruser

\e[0m
*****
*****

"
END
}

doNothing=0;
while [ -n "$1" ]; do
    case "$1" in
        -h | --help)
            myHelp
            exit
            ;;
        -n)
            doNothing=1;
            shift
            ;;
    esac 
done 

if [ $doNothing -gt 0 ]; then
    echo -e "****\nDoing nothing!\n****"
fi

export user=$(whoami)
echo " "  
echo " "
echo -e "                        Your \e[1;33musername is \e[0;34m-->> \e[1;31m$user"
echo " "
echo " "
echo -e "     \e[1;34m***************************************************"
echo "              |                                    |"
echo "              |        COLOUR USER SCRIPT          |"
echo -e "              \e[0;37m|        written by Kyilax           |"
echo -e "              \e[1;34m|         Github: kyilax             |"
echo "              |                                    |"
echo -e "      *****************************************************\e[0m"
